include: /.gitlab/.gitlab-ci.compose.yml

image: dtzar/helm-kubectl:3.3.0

stages:
  - deploy

# deploy stage steps:

gateway.deploy.k8s:
  stage: deploy
  tags:
    - k8s
    - gateway
  only:
    kubernetes: active
  except:
    changes:
      - "*.md"
  script:
    - helm upgrade --install -n gateway traefik-ingress traefik-ingress/