project: kicksware
component: proxy
nameOverride: ""
fullnameOverride: ""
baseDirL: &baseDir /source
sourceDir: &sourceDir /source/repos/kicksware-platform

replicaCount: 2
image:
  repository: traefik
  pullPolicy: IfNotPresent
  tag: v2.3

service:
  type: LoadBalancer
  port: 80
  securePort: 443
  adminPort: 8080
  addtPorts:
    - name: debug
      port: 4000

ingress:
  enabled: true
  entrypoints:
    - web
    - websecure
  routes:
    - host: proxy.kicksware.com
      paths:
        - /
      middlewares:
        - name: traefik-auth
      services:
        - name: api@internal
          namespace: default
          kind: TraefikService
          port: 8080
          scheme: http
  tls:
    enabled: true
    certResolver: le
    domains:
      - main: kicksware.com
        sans:
          - '*.kicksware.com'

api:
  insecure: true
  dashboard: true

log:
  level: INFO
  accesslog: true

volumes:
  - name: certs
    persistent:
      claim: traefik-certsclaim
      storageClass: nfs
      size: 1Gi
      accessModes:
        - ReadWriteOnce
    mountPath: /source/certs

providers:
  file:
    enabled: false
    directory: /source/dynamic-config
    watch: true
  kubernetescrd:
    enabled: true
  kubernetesingress:
    enabled: true

pilot:
  token: ae4f48c1-de07-4b07-87bd-cca466d22548

acme:
  enabled: true
  email: timothy@kicksware.com
  storage: /source/certs/acme.json
  dnsChallenge:
    enabled: true
    provider: digitalocean
    envName: DO_AUTH_TOKEN
    token: 6229b9e18dd51158da31da743bcf36262a11e8075a8ea2847d555cb9a3e47bf4


secrets:
  mounts:
    - name: grpc-tls
      mountPath: /source/keys

serverTransport:
  rootCAs:
    - /source/keys/tls.crt
  insecureSkipVerify: false

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 25
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

serviceAccount:
  create: true
  name: ""