stages:
  - deploy

variables:
  SOURCE_DIR: /source/repos/$CI_PROJECT_NAME

gateway.deploy.compose:
  image:
    name: docker/compose:1.25.0
  services:
    - docker:stable-dind
  stage: deploy
  tags:
    - compose
    - gateway
  except:
    kubernetes: active
  before_script:
    - cp -r /builds/root/* /source/repos/
    - apk add make
  script:
    - make gateway