apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "chart.fullname" . }}.nfs-claim
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi